#!/usr/bin/env bash
# Lore plugin — one-time credential setup.
#
# Reads LORE_API_KEY, LORE_APP, LORE_NAMESPACE from the environment (not CLI
# args, to keep secrets out of `ps` and shell history), writes them to
# ${CLAUDE_PLUGIN_DATA}/config.env with mode 600, and verifies the credentials
# with a test call to the Lore API.
#
# Invoked by the `lore-setup` skill. Not meant to be run by the user directly.

set -euo pipefail

: "${LORE_API_KEY:?Set LORE_API_KEY in the environment}"
: "${LORE_APP:?Set LORE_APP in the environment}"
: "${LORE_NAMESPACE:?Set LORE_NAMESPACE in the environment}"

LORE_API_BASE="${LORE_API_BASE:-https://api.lore.dev}"

CONFIG_DIR="${CLAUDE_PLUGIN_DATA:-$HOME/.claude/lore}"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.env"

umask 077
cat > "$CONFIG_FILE" <<EOF
# Generated by lore-plugin setup.sh — do not edit by hand.
# Re-run the lore-setup skill to change these values.
export LORE_API_KEY='$LORE_API_KEY'
export LORE_APP='$LORE_APP'
export LORE_NAMESPACE='$LORE_NAMESPACE'
export LORE_API_BASE='$LORE_API_BASE'
EOF
chmod 600 "$CONFIG_FILE"

echo "Config written to $CONFIG_FILE"
echo "Verifying credentials against $LORE_API_BASE..."

http_code=$(curl -sS -o /tmp/lore-setup-verify.$$ -w '%{http_code}' \
  -H "Authorization: Bearer $LORE_API_KEY" \
  "$LORE_API_BASE/v1/apps/$LORE_APP/namespaces/$LORE_NAMESPACE/index" || echo "000")

case "$http_code" in
  2*)
    rm -f /tmp/lore-setup-verify.$$
    echo "OK — connected to Lore as app=$LORE_APP namespace=$LORE_NAMESPACE"
    ;;
  401|403)
    echo "Error: API key rejected (HTTP $http_code). Check that LORE_API_KEY is correct and scoped to this app." >&2
    cat /tmp/lore-setup-verify.$$ >&2 2>/dev/null || true
    rm -f /tmp/lore-setup-verify.$$
    exit 1
    ;;
  404)
    echo "Error: app or namespace not found (HTTP 404). Check that LORE_APP='$LORE_APP' and LORE_NAMESPACE='$LORE_NAMESPACE' exist." >&2
    rm -f /tmp/lore-setup-verify.$$
    exit 1
    ;;
  000)
    echo "Error: could not reach $LORE_API_BASE. Check your network connection." >&2
    rm -f /tmp/lore-setup-verify.$$
    exit 1
    ;;
  *)
    echo "Error: unexpected HTTP $http_code from Lore API." >&2
    cat /tmp/lore-setup-verify.$$ >&2 2>/dev/null || true
    rm -f /tmp/lore-setup-verify.$$
    exit 1
    ;;
esac
